name: Refresh Prices

on:
  schedule:
    - cron: '0 3 * * *'  # every day at 03:00 UTC
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      KROGER_CLIENT_ID: ${{ secrets.KROGER_CLIENT_ID }}
      KROGER_CLIENT_SECRET: ${{ secrets.KROGER_CLIENT_SECRET }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run price refresh
        run: |
          PYTHONPATH=backend python backend/scripts/refresh_prices.py 